# permissions for end users to view simpleservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simpleserver-viewer-role
rules:
- apiGroups:
  - sandbox.example.com
  resources:
  - simpleservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sandbox.example.com
  resources:
  - simpleservers/status
  verbs:
  - get
